hicsail/nist-frontend

- src/App.tsx
- src/aws-client.ts
- src/components/FileUploader.tsx
- src/components/S3Display.tsx
- src/contexts/s3.context.tsx
- src/pages/Organization.tsx
* Provide context for S3 client
* Should reduce change of auth race conditions
> chore: S3 Context

- src/App.tsx
- src/components/S3Display.tsx
- src/components/UpdatePermissionsButton.tsx
- src/contexts/UI.tsx
- src/pages/Access.tsx
- src/pages/AccessManager.tsx
- src/pages/Dashboard.tsx
- src/pages/Organization.tsx
Sorry guys, I'll include the template for PRs next time but breadcrumbs added.
> Breadcrumbs added

- src/App.tsx
- src/contexts/theme.providers.tsx
* Add placeholder for MUI theming
* Wrap code in theme provider
> chore: MUI Theme

- index.html
- src/App.tsx
- src/contexts/theme.providers.tsx
- src/pages/AccessManager.tsx
- src/pages/Dashboard.tsx
- src/pages/Organization.tsx
- src/pages/error-route.tsx
* Add Typography setting to MUI Theme
* Change out manual headers for Typography
* Dashboard view looks slightly different with current typography
> chore: Typography

- src/components/OrganizationCard.tsx
- src/pages/Dashboard.tsx
Added some minor updates to the dashboard page. Basic styling with margins
> Dashboard org cards

- src/components/OrganizationCard.tsx
- src/pages/Organization.tsx
* Change out  how organization cards navigate to organization view
> bug: Organization Navigation

- src/aws-client.ts
- src/components/file-list-view.tsx
* Handle folder deletion
* Will delete all sub-files
> feat: Folder Deletion

- src/components/EnhancedTableHead.tsx
- src/components/file-list-view.tsx
- src/pages/Organization.tsx
* Sorting on name, size, last modified date
> feat: Sort on File Viewer

- src/pages/Organization.tsx
* Display the current folder name
> feat: Current Folder Name

- src/pages/Organization.tsx
* Clear new file input after upload
> bug: Clear File Input

- src/aws-client.ts
* Remove throwing error when an organization does not have data yet
> bug: Remove error on no contents

- src/components/file-list-view.tsx
* Add explicit support for DNA file type
> chore: Add DNA File Type Support

- src/components/FileSearch.tsx
- src/components/file-list-view.tsx
- src/pages/Organization.tsx
* Basic file searching implementation
* Navigates user to contained folder
> feat: File Searching

- .github/workflows/client.yml
- deployment/docker-compose-prod.yml
* Production docker compose
* Production build and deployment for GitHub actions
> chore: Production Deployment

- src/components/OrganizationCard.tsx
- src/pages/Dashboard.tsx
* Fix bucket names
* Remove no access hard coding
> bug: Fix Bucket Names

- src/pages/AccessManager.tsx
- Temporary fix of searching on permission page and changing permission
- Functionally working.
- May need to refactor files for permission page for better optimization and organization.
> fix: temp fix of permission search

- src/aws-client.ts
* Temporary fix for valid download
> bug: Change to URL based download

- .github/workflows/client.yml
- .prettierrc
- package-lock.json
- package.json
- src/App.tsx
- src/components/EnhancedTableHead.tsx
- src/components/FileSearch.tsx
- src/components/FileUploader.tsx
- src/components/OrganizationCard.tsx
- src/components/SequenceViz.tsx
- src/components/SideNav.tsx
- src/components/UpdatePermissionsButton.tsx
- src/components/UserPermissionsTable.tsx
- src/components/file-list-view.tsx
- src/contexts/Auth.tsx
- src/contexts/Permissions.tsx
- src/contexts/UI.tsx
- src/contexts/organization.context.tsx
- src/contexts/s3.context.tsx
- src/main.tsx
- src/pages/AccessManager.tsx
- src/pages/Callback.tsx
- src/pages/Dashboard.tsx
- src/pages/Login.tsx
- src/pages/Organization.tsx
- src/pages/error-route.tsx
- yarn.lock
* Add prettier script
* Add formatting as a check to workflow
> chore: Linting

- src/App.tsx
- src/contexts/User.tsx
- src/graphql/graphql.ts
- src/graphql/user/user.graphql
- src/graphql/user/user.ts
> user context added to make user data accessible throughout authenticated routes

- src/components/JupyterNotebook.tsx
- src/graphql/graphql.ts
- src/graphql/jupyterhub/jupyterhub.graphql
- src/graphql/jupyterhub/jupyterhub.ts
- src/pages/Organization.tsx
* Jupyter Notebook view in iframe
> feat: Jupyter Plugin
